# ESS MVP Configuration - IMPROVED for better results

# Simulation period - avoiding DST transition
period:
  start_date: "2024-01-10"  # Avoid March DST transition
  num_days: 300  # Shorter period for testing
  # end_date: "2024-01-31"

# Household consumption
consumption:
  profile_file: "data/e_redes_perfil_consumo.xlsx"
  profile_column: "BTN A"  # Residential profile
  annual_consumption_kwh: 7000  # More typical residential consumption
  consumption_model: true  # Use 2024 profile for any simulation year

# Electricity tariff
tariff:
  type: "indexed"  # or "bi_horaria"
  
  indexed:
    margin_eur_mwh: 0  # Slightly higher retailer margin
    grid_fees_eur_kwh: 0.00  # Grid access and system fees
    
  bi_horaria:
    peak_price_eur_kwh: 0.20 
    off_peak_price_eur_kwh: 0.10
    peak_hours: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    
  vat_rate: 0.23  # 23% VAT in Portugal

# Contracted power
power_contract:
  contracted_power_kva: 6.9  # Typical residential
  daily_fixed_cost_eur: 0.30  # Fixed daily charge

# Battery specifications - more realistic sizing
battery:
  capacity_kwh: 50.0  # Smaller battery for residential
  soc_init: 0.5  # Start at 50% charge
  max_charge_kw: 5.0  # 5kW charge rate
  max_discharge_kw: 5.0  # 5kW discharge rate
  efficiency: 0.92  # Slightly higher efficiency
  soc_min: 0.20  # 15% minimum SOC (more usable capacity)
  soc_max: 0.80  # 95% maximum SOC (avoid overcharging)
  
  # Economic parameters
  capex_eur: 5000  
  lifetime_years: 12
  degradation_cost_eur_kwh: 0.01  # Lower degradation cost

# Control strategy - LESS AGGRESSIVE settings
strategy:
  type: "optimal"  # Start with arbitrage, not optimal
  allow_grid_export: false
  
  arbitrage:
    charge_threshold_percentile: 20  # Only charge in bottom 20% of prices
    discharge_threshold_percentile: 80  # Only discharge in top 20% of prices
    min_price_spread_eur_mwh: 30  # Higher minimum spread (30 EUR/MWh)
    lookahead_hours: 24  # 24-hour lookahead
    
  optimal:
    optimization_window_hours: 24  # Shorter optimization window
    use_simple_optimization: false  # Try PuLP first
    
  peak_shaving:
    target_peak_kw: 4.0  # Lower peak target
    
# Output options
output:
  save_timeline: true
  timeline_file: "outputs/corrected_simulation_timeline.csv"
  save_summary: true
  summary_file: "outputs/corrected_simulation_summary.json"
  generate_plots: true
  plots_dir: "outputs/plots/"

# Additional settings for better results
simulation:
  validation_mode: true
  max_strategy_errors: 10  # Stop if too many errors
  fallback_to_simple: true  # Use simple strategy if optimization fails