# ESS MVP Configuration - Energy Arbitrage Scenario

# Simulation period
period:
  start_date: "2024-03-01"
  num_days: 2  # Or use end_date instead
  # end_date: "2024-01-31"

# Household consumption
consumption:
  profile_file: "data/e_redes_perfil_consumo.xlsx"
  profile_column: "BTN A"  # Residential profile
  annual_consumption_kwh: 14650  # 10 kWh/day average

# Electricity tariff
tariff:
  type: "indexed"  # or "bi_horaria"
  
  indexed:
    margin_eur_mwh: 10  # Retailer margin (10 EUR/MWh = 0.01 EUR/kWh)
    grid_fees_eur_kwh: 0.05  # Grid access and system fees
    
  bi_horaria:
    peak_price_eur_kwh: 0.20
    off_peak_price_eur_kwh: 0.10
    peak_hours: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    
  vat_rate: 0.23  # 23% VAT in Portugal

# Contracted power
power_contract:
  contracted_power_kva: 6.9  # Typical residential
  daily_fixed_cost_eur: 0.30  # Fixed daily charge

# Battery specifications
battery:
  capacity_kwh: 40.0
  soc_init: 0.5  # Start at 50% charge
  max_charge_kw: 5.0
  max_discharge_kw: 5.0
  efficiency: 0.9  # 90% round-trip efficiency
  soc_min: 0.2  # 20% minimum SOC
  soc_max: 0.8  # 90% maximum SOC
  
  # Economic parameters
  capex_eur: 8000  # Total investment cost
  lifetime_years: 10
  degradation_cost_eur_kwh: 0.02  # Cost per kWh cycled

# Control strategy
strategy:
  type: "optimal"  # "arbitrage", "optimal", or "peak_shaving"
  
  arbitrage:
    charge_threshold_percentile: 30  # Charge when price is in bottom 30%
    discharge_threshold_percentile: 70  # Discharge when price is in top 30%
    min_price_spread_eur_mwh: 20  # Minimum spread to trigger action
    
  peak_shaving:
    target_peak_kw: 4.5  # Try to keep peak below this
    
# Output options
output:
  save_timeline: true
  timeline_file: "outputs/simulation_timeline.csv"
  save_summary: true
  summary_file: "outputs/simulation_summary.json"
  generate_plots: true
  plots_dir: "outputs/plots/"