# ESS MVP Configuration - IMPROVED for better results

# Simulation period - avoiding DST transition
period:
  start_date: "2023-01-10"  # Avoid March DST transition
  num_days: 900  # Shorter period for testing
  # end_date: "2024-01-31"

# Household consumption
consumption:
  profile_file: "data/e_redes_perfil_consumo.xlsx"
  profile_column: "BTN A"  # Residential profile
  annual_consumption_kwh: 7000  # More typical residential consumption
  consumption_model: true  # Use 2024 profile for any simulation year

# Electricity tariff
tariff:
  type: "indexed"  # or "bi_horaria"
  
  indexed:
    k1: 1.28
    k2_eur_kwh: 0.0172
    k3_eur_day: 0.09410
    losses_pct: 0.085
    option: "bi"           # simples, bi or tri
    cycle: "daily"         # daily or weekly
    tariff_energy_eur_kwh:
      simples: 0.0600
      bi:
        fora_vazio: 0.0830
        vazio: 0.0149
      tri:
        ponta: 0.2469
        cheias: 0.0388
        vazio: 0.0149
    tariff_power_eur_kva_day: 0.31
    
  vat_rate: 0.23  # 23% VAT in Portugal

# Contracted power
power_contract:
  contracted_power_kva: 6.9  # Typical residential

# Battery specifications - more realistic sizing
battery:
  capacity_kwh: 50.0  # Smaller battery for residential
  soc_init: 0.5  # Start at 50% charge
  max_charge_kw: 5.0  # 5kW charge rate
  max_discharge_kw: 5.0  # 5kW discharge rate
  efficiency: 0.92  # Slightly higher efficiency
  soc_min: 0.20  # 15% minimum SOC (more usable capacity)
  soc_max: 0.80  # 95% maximum SOC (avoid overcharging)
  
  # Economic parameters
  capex_eur: 5000  
  lifetime_years: 12
  degradation_cost_eur_kwh: 0.01  # Lower degradation cost

# Control strategy - LESS AGGRESSIVE settings
strategy:
  type: "optimal"  # Start with arbitrage, not optimal
  allow_grid_export: false
  
  arbitrage:
    charge_threshold_percentile: 20  # Only charge in bottom 20% of prices
    discharge_threshold_percentile: 80  # Only discharge in top 20% of prices
    min_price_spread_eur_mwh: 30  # Higher minimum spread (30 EUR/MWh)
    lookahead_hours: 24  # 24-hour lookahead
    
  optimal:
    optimization_window_hours: 24  # Shorter optimization window
    use_simple_optimization: false  # Try PuLP first
    
  peak_shaving:
    target_peak_kw: 4.0  # Lower peak target
    
# Output options
output:
  save_timeline: true
  timeline_file: "outputs/corrected_simulation_timeline.csv"
  save_summary: true
  summary_file: "outputs/corrected_simulation_summary.json"
  generate_plots: true
  plots_dir: "outputs/plots/"

# Additional settings for better results
simulation:
  validation_mode: true
  max_strategy_errors: 10  # Stop if too many errors
  fallback_to_simple: true  # Use simple strategy if optimization fails